name: dirtyp
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal
  - fastp
  - minimap2
  - samtools
  - mosdepth
  - csvtk
  - pandas
  - r-base=4.1
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-optparse
  - r-pacman
  - r-cowplot
